### ISSUE TITLE
Window issue

### ISSUE THREAD

**Issue by BananaSoftwaree** [Wolfyxon/plexus-gen#1]
Well look at the picture below (the about window):

![image](https://user-images.githubusercontent.com/93658686/152775828-127d28d1-3cf7-4d02-bce3-18335ee68922.png)

I know it doesn't affect to generator system, but I will show you as bug lol
And why clicking outside will close that window?

**Comment by Wolfyxon** [comment]
I can't fix this, the window will always ignore z-index. It appears as new node when being shown

**Comment by BananaSoftwaree** [comment]
Okay lol
